"""empty message

Revision ID: 9092930fa3ba
Revises: f5db7181b83e
Create Date: 2022-05-24 15:02:15.896790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9092930fa3ba'
down_revision = 'f5db7181b83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('quatity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'quatity')
    # ### end Alembic commands ###
