"""empty message

Revision ID: ed14b2e0c316
Revises: 456654f005ea
Create Date: 2022-04-22 15:11:45.538184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed14b2e0c316'
down_revision = '456654f005ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('gender', sa.String(length=550), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'gender')
    # ### end Alembic commands ###
