"""empty message

Revision ID: f579ed9ad180
Revises: 9092930fa3ba
Create Date: 2022-05-31 22:34:44.436972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f579ed9ad180'
down_revision = '9092930fa3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('quantity', sa.Integer(), nullable=True))
    op.drop_column('favorite', 'quatity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('quatity', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('favorite', 'quantity')
    # ### end Alembic commands ###
